# Generated by Django 4.2.2 on 2023-06-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='scientifc_name',
            new_name='scientific_name',
        ),
    ]
