# Generated by Django 4.2.2 on 2023-06-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_scientifc_name_group_scientific_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
